" Matt's .vimrc
" must be symlinked to $HOME/.vimrc for Vundle
"

" fix yosemite bullshit
if has("gui_macvim")
    set shell=/bin/bash\ -l
endif

set nocompatible              " be iMproved, required


" Emacs keys please
" use vimacs instead
" cnoremap <C-a>  <Home>
" noremap <C-e>  <End>
" noremap <C-b>  <Left>
" noremap <C-f>  <Right>
" noremap <C-d>  <Delete>
" noremap <M-b>  <S-Left>
" noremap <M-f>  <S-Right>
" noremap <M-d>  <S-right><Delete>
" noremap <Esc>b <S-Left>
" noremap <Esc>f <S-Right>
" noremap <Esc>d <S-right><Delete>
" noremap <C-g>  <C-c>

" interface
colorscheme wombat
if has("gui_running")
	if has("gui_gtk2")
		set guifont=Monospace\ 10
	elseif has("gui_macvim")
		set guifont=Monaco:h12
	endif
endif
set guioptions+=c
set guioptions-=T  "remove toolbar
set guioptions-=r  "remove right-hand scroll bar
set guioptions-=L  "remove left-hand scroll bar
set title
set modeline
set modelines=2
set switchbuf=usetab
set ruler
set shortmess+=I
set background=dark
set cursorline
set lazyredraw
set number
set showcmd
set showmatch  " highlight matching parens
let g:session_autosave = 'no'
" put viminfo inside the vim directory
set viminfo+=n~/.vim/viminfo

" highlight 80 chars overflow
" set colorcolumn=80
set textwidth=79

" basic editing setup
set smartindent
set autoindent

set tabstop=4
set softtabstop=4
" set expandtab "tabs to spaces

au FileType c setl sw=8 sts=8
au FileType java setl sw=4 sts=4

au FileType haskell sw=2 sts=2 et
au FileType lithaskell sw=2 sts=2 et

au FileType sh setl sw=2 sts=2 et
au FileType javascript setl sw=2 sts=2 et
au FileType ruby setl sw=2 sts=2 et
au FileType eruby setl sw=2 sts=2 et
au FileType css setl sw=2 sts=2 et
au FileType scss setl sw=2 sts=2 et
au FileType html setl sw=2 sts=2 et wrap tw=0 wrapmargin=0 lbr
au FileType jade setl sw=2 sts=2 et wrap tw=0 wrapmargin=0 lbr
au FileType coffee setl sw=2 et

" delete trailing whitespace on save
autocmd BufWritePre <buffer> :%s/\s\+$//e

set shiftwidth=4

set ignorecase
set smartcase

set hidden
set history=1000

" set linebreak
" set wrap

syntax on
filetype on
filetype indent on

set foldenable
set foldlevelstart=10
set foldnestmax=10

" default is unix
set fileformats=unix,mac,dos

" stfu, dont beep
set visualbell
set noeb vb t_vb=

set mouse=a

set cmdheight=1

set laststatus=2
set t_Co=256

" Intuitive backspacing in insert mode
set backspace=indent,eol,start

" File-type highlighting and configuration.
" Run :filetype (without args) to see what you may have
" to turn on yourself, or just set them all to be sure.
syntax on
filetype on
filetype plugin on
filetype indent on

" Highlight search terms...
set hlsearch
set incsearch " ...dynamically as they are typed.

nnoremap ' `
nnoremap ` '
let mapleader = ","

" mouse in terminal?
set mouse=a
set mousehide
set mousem=popup

" tab complete
set wildchar=<Tab>
set wildmenu
set wildmode=longest:full,list:full
set wildignore+=*.a,*.o
set wildignore+=*.bmp,*.gif,*.ico,*.jpg,*.png
set wildignore+=.DS_Store,.git,.hg,.svn
set wildignore+=*~,*.swp,*.tmp

" Vundle
"if !isdirectory(expand("~/.vim/bundle/vundle/.git"))
"   !git clone https://github.com/gmarik/vundle ~/.vim/bundle/vundle
"endif

filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Emacs keys are a must
" Plugin 'andrep/vimacs'

" VimMarkDown: syntax for markdown
Plugin 'plasticboy/vim-markdown'

" Powerline: fancy command line
Plugin 'Lokaltog/vim-powerline'

" Plugin 'kien/ctrlp.vim'

" Yankstack: add a kill ring
Plugin 'maxbrunsfeld/vim-yankstack'

" PureScript-mode
Plugin 'purescript-vim'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

" init powerline
let g:Powerline_symbols = 'compatible'
