#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

xmodmap $HOME/.Xmodmap

[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources 
#choose. last as default


# Here awsome is kept as default
session=${1:-aw}

case $session in
    enl) exec enlightenment_start;;
    flux) exec startfluxbox;;
    gnome) exec gnome-session;;
    lxde) exec startlxde;;
    kde) exec kdeinit4;;
    xfce) exec startxfce4;;

    dwm) exec dwm;;
    twm) exec twm;;
    ob) exec openbox-session;;
    aw) exec awesome;;
    # No known session, try to run it as command
    *) exec $1;;                
esac
